### ISSUE TITLE
Installing this plugin breaks LTI outtcomes grade syncing

### ISSUE THREAD

**Issue by mwarner** [itamart/moodle-block_mhaairs#11]
Thank you for building this block/plugin.  It looks to be what I've been looking for.

However, when I installed it on my Moodle instances, the LTI outcomes grade transfer broke.  The Moodle LTI outcomes service endpoint (/mod/lti/service.php) returns a 404.   I haven't had time to investigate yet, but wanted to open a ticket in case you may know right away what the cause may be.

Thank you,
Mike

**Comment by itamart** [comment]
We haven't encountered any such issue so far. And when you uninstall the block the lti service returns to work?

**Comment by mwarner** [comment]
Interesting.  I uninstalled the block, but the problem persists.  I grabbed a fresh download of moodle and diffed it to what I've got, and the only difference was config.php, as expected.  Maybe something in the general block installation process is changing something in the database that the LTI service.php needs.

**Comment by mwarner** [comment]
Hmm...not sure how it happened, but the consumer secret for the External Tool type was not correct.  No idea why we didn't run into this as an issue before.

Sorry for thinking that it was your plugin.  As far as I knew, that was the only thing that had changed.

Mike
