### ISSUE TITLE
Identity type ignored in GetUserInfo

### ISSUE THREAD

**Issue by itamart** [itamart/moodle-block_mhaairs#8]
From Vadim:
Authorization connector has “identity_type” property, which is not being treated in plugin (GetUserInfo entry point). If its value is “internal”, the plugin should assume the user id being passed is an internal user id, otherwise – user name. Similar thing exists in gradebook for reference, except that gradebook also allows “lti” value.

**Comment by RanQTGIT** [comment]
where do you find the token user id?

**Comment by itamart** [comment]
The token user id is contained in the token that is passed to the service call. If the test is via the UI, the token is generated by the Connnector. We need Vadim to advise how the token is created on the Connector side.
